[build]
    base = ""
    publish = "dist/"
    command = "npm run build"

[dev]
  command = "npm run start"
  publish = "dist/"

[[headers]]
  for = "/assets/*/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000,
    immutable'''